import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Nav from '../components/nav'


export default function Home() {
  return (
    <div >
      <Head>
        <title>hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header/>
      {/* Nav */}
      <Nav/>
      {/* Result */}

    </div>
  )
}
