import Head from 'next/head'
import Banner from '../components/airbnb/banner'
import Header from '../components/airbnb/header'


export default function Home() {

  return (
    <div className='bg-white'>
      
      <Head>
        <title>airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header/>
      <Banner/>
   <main className='max-w-7xl mx-auto px-8 sm:px-16'>
     <section className='pt-6'>
     <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>
 
     </section>  </main>
   
    </div>
  )
}

